### ISSUE TITLE
Override inline styles

### ISSUE THREAD

**Issue by eseQ** [theKashey/used-styles#15]
Hello. I want to describe a simple case. Imagine:
Page on an initial state has simple div with class `my-box` and style
```CSS
.my-box {
  margin: 0 auto;
}
```
We already get this style as critical in `<style></style>` tag.
Later we did API-request add '.extra-class' to our div with 'my-box' class.
```CSS
.extra-class {
  margin: 10px 20px;
}
```
Now we have `.my-box` class in `style` tag with hight priority, `.my-box` and `.extra-class` in CSS file. And margin from `.extra-class` will be ignore.
Does exist some way to manage inline styles maybe? For ex:
1) Prepare multiple `style` tags by `getCriticalStyles` split by source with `data-used-styles`
2) Remove this style after load equal CSS file.

What kind of pitfalls did I miss?
