### ISSUE TITLE
media query support

### ISSUE THREAD

**Issue by hnrchrdl** [theKashey/used-styles#21]
are media queries supposed to be supported by this library?  I guess not properly, I do not seem to get any critical css for selectors that are behind media queries.

**Comment by theKashey** [comment]
Should work, there is even an issue about the cases when it should not - https://github.com/theKashey/used-styles/issues/10

However add I've added a few test to double check, and they are all green.

**Comment by hnrchrdl** [comment]
thanks a lot for looking into this. tests look good.
the problem is with filtering used selectors, at least when using `criticalStylesToString`. 

for example considering the following css
```css
h1 {
  margin-top: 50px;
}
h1 {
  @include breakpoint(small only) {
    margin-top: 30px;
  }
}
```
it would only interleave the first rule. the second one with the media query is filtered because the selector was already used.
