### ISSUE TITLE
Styles with same selector and content but different media are missing

### ISSUE THREAD

**Issue by theKashey** [theKashey/used-styles#31]
Given
```css
.content {    
}

@media screen and (min-width: 768px) {
    .content {
        grid-column:1/6
    }
}

@media screen and (min-width: 1024px) {
    .content {
        grid-column:1/7
    }
}

/*this style duplicates 768 one, had the hash before*/
@media screen and (min-width: 1600px) {
    .content {
        grid-column:1/6
    }
}
```
The last style will be missing due to hash collide between `768px` and `1600px` media
